[project]
name = "qterbot"
version = "0.1.0"
description = "A discord bot that answers questions about the Qter project using AI"
authors = [
    {name = "Henry Rovnyak",email = "h.rovnyak@proton.me"}
]
requires-python = ">=3.14"
dependencies = [
    "qdrant-client (>=1.19.0,<2.0.0)",
    "sentence-transformers (>=6.0.0,<7.0.0)",
    "polars (>=1.44.1,<2.0.0)",
    "altair (>=6.2.2,<7.0.0)",
    "ipython (>=9.17.0,<10.0.0)",
    "jupyterlab (>=4.6.3,<5.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.pytest.ini_options]
testpaths = ["tests"]


[dependency-groups]
dev = [
    "pytest (>=8,<10)"
]
